name: Build Test and Deploy

on:
  pull_request:
    branches:
      - master
      - dev
  push:
    branches:
      - master
      - dev

jobs:
  Build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.7", "3.8", "3.9"]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Git Branch Name
        uses: EthanSK/git-branch-name-action@v1
      - name: Echo the branch name
        run: echo "Branch name ${GIT_BRANCH_NAME}"
      - uses: actions/checkout@v2
      - name: Setup conda env
        uses: conda-incubator/setup-miniconda@v2
        with: 
          miniconda-version: "latest"
          mamba-version: "*"
          use-mamba: true
          channels: conda-forge, usgs-astrogeology
          channel-priority: strict
          activate-environment: test_env
          environment-file: environment.yml
          python-version: ${{ matrix.python-version }}
      - name: Install Python Package
        run: |
          conda install pip setuptools
          conda install --quiet pytest pytest-cov nbsphinx
          python setup.py install
      - name: Check build environment
        run: |
          conda list
          conda info
      - name: Test Python Package
        run: |
          pytest --cov libpyhat
#       - name: Deploy
#         if: ${{ env.GIT_BRANCH_NAME == 'master' }}
#         run: |
#           echo "We are on the master branch - deploying!"
#           conda deactivate
#           conda install conda-build anaconda-client
#           conda config --set anaconda_upload yes
#           conda build --token ${{ secrets.CONDA_UPLOAD_TOKEN }} --python $PYTHON_VERSION ../../recipe
          
          
      - name: Deploy
        # You may pin to the exact commit or the version.
        # uses: uibcdf/action-build-and-upload-conda-packages@f1d3918a219be72a21648fc935e30e5c8b9079fe
        uses: uibcdf/action-build-and-upload-conda-packages@v1.1-beta.1
        with:
          # Path to the directory in the repository where the meta.yaml file is located.
          meta_yaml_dir: recipe
          # Python version of the package to be built.
          python-version: $PYTHON_VERSION
          # Name of the Anaconda user or organization where the conda package will be published.
          user: usgs-astrogeology
          # Token to access to anaconda cloud.
          token: ${{ secrets.CONDA_UPLOAD_TOKEN }}
      - name: Other branch message
        if: ${{ env.GIT_BRANCH_NAME != 'master' }}
        run: echo 'Not on the master branch - not deploying'
      
